# Generated by Django 4.1.7 on 2023-03-12 20:09

import creditcards.models
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('number', creditcards.models.CardNumberField(blank=True, max_length=20, null=True)),
                ('expire_date', creditcards.models.CardExpiryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=255, null=True, region=None)),
                ('post_code', models.CharField(blank=True, max_length=6, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='User', serialize=False, to='BookingMuseum.user_info')),
                ('credit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='User_credit_info', to='BookingMuseum.credit')),
            ],
        ),
        migrations.CreateModel(
            name='Museum_Ticket_Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tickets_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Museum_Ticket_Reservation', to='BookingMuseum.user')),
            ],
        ),
    ]
