# Generated by Django 4.1.7 on 2023-03-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingMuseum', '0003_alter_ticket_reservation_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_reservation',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
