# Generated by Django 4.1.7 on 2023-03-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingMuseum', '0004_alter_ticket_reservation_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_reservation',
            name='type',
            field=models.CharField(blank=True, choices=[('Egyptian_Citizen', 'Egyptian_Citizen '), ('Egyptian_Student', 'Egyptian_Student(5)'), ('Foreign_Visitor', 'Foreign_Visitor(100)'), ('Foreign_Student', 'Foreign_Student(50)'), ('photographic_camera', 'photographic_camera(50)')], max_length=255, null=True),
        ),
    ]
