# Generated by Django 4.1.7 on 2023-03-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingMuseum', '0006_remove_ticket_reservation_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_reservation',
            name='price',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=20),
        ),
        migrations.AlterField(
            model_name='ticket_reservation',
            name='type',
            field=models.CharField(blank=True, choices=[('Egyptian_Citizen', 'Egyptian_Citizen(20)'), ('Egyptian_Student', 'Egyptian_Student(5)'), ('Foreign_Visitor', 'Foreign_Visitor(100)'), ('Foreign_Student', 'Foreign_Student(50)'), ('photographic_camera', 'photographic_camera(50)')], max_length=255, null=True),
        ),
    ]
