# Generated by Django 4.1.7 on 2023-03-08 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CH', 'Chariot'), ('PN', 'Painting'), ('ST', 'Status'), ('HO', 'Holding'), ('BC', 'Borrowed_Collection'), ('PC', 'Permanent_Collection'), ('OR', 'Other')], max_length=2, null=True)),
                ('country_of_orgin', models.CharField(blank=True, max_length=255, null=True)),
                ('reign', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('halls_number', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
