# Generated by Django 4.1.7 on 2023-03-14 13:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ArtObject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtStory',
            fields=[
                ('story', models.TextField(blank=True, null=True)),
                ('art_object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Art_Story', serialize=False, to='ArtObject.artobject')),
            ],
        ),
        migrations.CreateModel(
            name='Borrowed_Collection',
            fields=[
                ('date_borrowed', models.DateTimeField(blank=True, null=True)),
                ('date_returned', models.DateTimeField(blank=True, null=True)),
                ('art_object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Borrowed_Collection', serialize=False, to='ArtObject.artobject')),
            ],
        ),
        migrations.CreateModel(
            name='Chariot',
            fields=[
                ('object_number', models.IntegerField(blank=True, null=True)),
                ('chassis_number', models.CharField(blank=True, max_length=255, null=True)),
                ('country_of_orgin', django_countries.fields.CountryField(blank=True, max_length=255, null=True)),
                ('reign', models.CharField(blank=True, max_length=255, null=True)),
                ('art_object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Chariot', serialize=False, to='ArtObject.artobject')),
            ],
        ),
        migrations.CreateModel(
            name='other',
            fields=[
                ('object_number', models.IntegerField(blank=True, null=True)),
                ('art_object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Other', serialize=False, to='ArtObject.artobject')),
            ],
        ),
        migrations.CreateModel(
            name='painting',
            fields=[
                ('artist_name', models.CharField(blank=True, max_length=255, null=True)),
                ('art_object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Painting', serialize=False, to='ArtObject.artobject')),
            ],
        ),
        migrations.CreateModel(
            name='Permenant_Collection',
            fields=[
                ('date_aquired', models.DateTimeField(blank=True, null=True)),
                ('art_object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Permenant_Collection', serialize=False, to='ArtObject.artobject')),
            ],
        ),
        migrations.RenameField(
            model_name='artobject',
            old_name='country_of_orgin',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='artobject',
            name='reign',
        ),
        migrations.RemoveField(
            model_name='description',
            name='id',
        ),
        migrations.AddField(
            model_name='artobject',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artobject',
            name='date_modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='artobject',
            name='hall',
            field=models.ForeignKey(default='8', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Art_Object', to='ArtObject.hall'),
        ),
        migrations.AddField(
            model_name='description',
            name='art_object',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Description', serialize=False, to='ArtObject.artobject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artobject',
            name='type',
            field=models.CharField(blank=True, choices=[('CH', 'Chariot'), ('PN', 'Painting'), ('ST', 'Status'), ('HO', 'Holding'), ('BC', 'Borrowed_Collection'), ('PC', 'Permanent_Collection'), ('OR', 'Other')], max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(blank=True, max_length=255, null=True)),
                ('art_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Holding', to='ArtObject.artobject')),
            ],
        ),
    ]
