# Generated by Django 4.1.7 on 2023-03-20 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArtObject', '0003_alter_artobject_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hall',
            old_name='halls_number',
            new_name='hall_number',
        ),
    ]
