# Generated by Django 4.1.7 on 2023-03-08 18:39

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Museum_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=255, null=True, region=None)),
                ('about', models.TextField(blank=True, null=True)),
                ('halls_number', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('museum_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='InfoMuseum.museum_info')),
            ],
        ),
        migrations.CreateModel(
            name='Openning_Hour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('FR', 'Friday'), ('ST', 'Saturday'), ('SN', 'Sunday'), ('MN', 'Monday'), ('TU', 'Tuseday'), ('WE', 'Wednesday'), ('TH', 'Thursday')], max_length=2, null=True)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('museum_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openning_Hours', to='InfoMuseum.museum_info')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.ImageField(blank=True, null=True, upload_to='images')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('museum_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='InfoMuseum.museum_info')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('event_about', models.TextField(blank=True, null=True)),
                ('museum_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Events', to='InfoMuseum.museum_info')),
            ],
        ),
    ]
