# Generated by Django 4.1.7 on 2023-03-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfoMuseum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openning_hour',
            name='day',
            field=models.CharField(choices=[('FR', 'Friday'), ('ST', 'Saturday'), ('SN', 'Sunday'), ('MN', 'Monday'), ('TU', 'Tuseday'), ('WE', 'Wednesday'), ('TH', 'Thursday')], max_length=10, null=True),
        ),
    ]
